language: generic
env:
  global:
    - secure: "iS4tcrwKeC6myLPHv4K63bgR6wqbJ6fioNHMaIDFTmgA5FnpBwT/YmIdNHPfI/zGHl4M5JfMZ4nR/vF6EceyGNvE2ucLO7XnxSxPEFfneckZbC8c9S/MXMQ009+IbphRExBWX1clHYecULc4lhDQyiDjQkUO5mC8yu4f05oe45E1wVAmVmmJ35FU2m4tZuv9Y0RFyxJu+EmYqhYI5BvIzmSN7ajDIUZa5FKBeBQrN5pn+9RJnniykgDrLsmaf6APauEthKrcZhb0J6fKC813OaFMIxcHEsCjbICwJk30LjIXZVXweHlHF3BaeDTB2wNooPIY01d2XLV3Zcy4vmrw6nMOdIx3bKCEyEIp8Wqh2fXh2H+7HfCtpn3vXYS0RP1JJGZQoLj8tXQz33P7jjCyixlm1bI8l6GjysJRQTDrG+2MTAxNDJatzcM1f/UidBt3MxrZo3M+w4i1h7eDLKvD0jkXoQ1bEWcQS0Ak1FgN3/1UKF5W6cEQHNUeWOVWEsP3cA3F4rEOnlpttcfTDWzNtGnsbUMG+WJZldm+y+TWTzAQiiGVXKUyBBiDMi+0t871/ich208LrgEfmHwOOo3nP1xknVKtDRCNojetT1siBcjR9FSI1xsi5MRuVkBEohb/go5Lj5rdE3JVXJGV3tzxf3PjJYwQSw0H3n3ZV23ys5k="
matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker

    - os: osx
      compiler: clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      docker build -t bioasp/caspo-conda ./travis-ci/;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  - conda config --set show_channel_urls true
  - conda update --yes conda
  - conda install --yes conda-build jinja2 anaconda-client
  - conda config --add channels conda-forge
  - conda config --add channels svidela

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run -v ${TRAVIS_BUILD_DIR}:/work-dir -w /work-dir bioasp/caspo-conda bash -cxe "conda build ./recipe; ./travis-ci/cp_artifacts.py";
    else
      conda build recipe;
      ./travis-ci/cp_artifacts.py;
    fi

after_success:
  - ./travis-ci/upload.py
