name: Release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sed -i "s:9999:${VERSION//*v/}:" caspo/__init__.py recipe/meta.yaml
      env:
          VERSION: ${{ github.ref }}
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*
  conda-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sed -i "s:9999:${VERSION//*v/}:" caspo/__init__.py recipe/meta.yaml
      env:
          VERSION: ${{ github.ref }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
          python-version: "3.12"
    - name: prepare
      run: |
        conda install -y python=3.12 anaconda-client conda-build conda-verify
        conda config --set anaconda_upload yes
    - name: build
      run: |
        cd recipe
        conda build --user colomoto --token $ANACONDA_TOKEN -c defaults -c conda-forge -c potassco .
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    - name: Trigger Docker building
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.PAT }}
          event-type: docker
          client-payload: '{"ref": "${{ github.ref }}"}'
