name: Test package

on: [push, pull_request]

jobs:
  pypi-test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build
      run: |
        python -m build
  conda-test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3
      with:
          python-version: "3.12"
    - name: prepare
      run: |
        conda install -y python=3.12 anaconda-client conda-build conda-verify
        conda config --set anaconda_upload no
    - name: build
      run: |
        cd recipe
        conda build -c defaults -c conda-forge -c potassco .
